apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fastapi-app-role
rules: [] # No permissions needed for the application itself

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fastapi-app-rolebinding
subjects:
- kind: ServiceAccount
  name: fastapi-app-sa
  apiGroup: ""
roleRef:
  kind: Role
  name: fastapi-app-role
  apiGroup: rbac.authorization.k8s.io
